/*
 * Automatically generated C config: don't edit
 * Zmodo App Configuration
 * Tue Apr 21 07:13:44 2020
 */

#ifndef ZMD_APP_AUTO_CONFIG
#define ZMD_APP_AUTO_CONFIG

#define ZMD_APP_HI3519A100 1
#define ZMD_APP_HARDWARE_VERSION "V0.0.0.01"
#define ZMD_APP_DEBUG_ITF 1
#define ZMD_APP_RTSP 1
#define ZMD_APP_DEBUG_ZSP 1
#define ZMD_APP_SOFTWARE_VERSION "V0.0.0.01"
#define ZMD_APP_ENCODE_VIDEO 1
#define ZMD_APP_DEBUG_BUF 1
#define ZMD_APP_ENCODE 1
#define ZMD_APP_ENCODE_BUFFERMANAGE 1
#define ZMD_APP_ENCODE_VIDEO_MAX_CH_SRTEAM 1
#define ZMD_APP_THI_MBEDTLS 1
#define ZMD_APP_DEBUG 1
#define ZMD_APP_DEBUG_VID 1
#define ZMD_APP_THREADPOOL 1
#define ZMD_APP_HISI 1
#define ZMD_APP_HISI_LINUX 1
#define ZMD_APP_ZSP 1

#endif  /* ZMD_APP_AUTO_CONFIG */
